import { RiskZone, District, VulnerableRoad, VulnerableVillage, HistoricalLandslideEvent } from "@/types/geo";

export interface InfrastructureAsset {
  id: string;
  districtId: string;
  name: string;
  category: "BRIDGE" | "POWER_SUBSTATION" | "TELECOM_TOWER" | "HOSPITAL" | "SHELTER";
  location: { latitude: number; longitude: number };
  vulnerabilityRating: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  status: "OPERATIONAL" | "IMPAIRED" | "AT_RISK";
  details: string;
}

export const NER_DISTRICT_BOUNDS: Record<string, { lat: number; lng: number; zoom: number; name: string; state: string }> = {
  all: { lat: 25.5788, lng: 91.8933, zoom: 7, name: "All North East Region", state: "NER" },
  aizawl: { lat: 23.7271, lng: 92.7176, zoom: 11, name: "Aizawl District", state: "Mizoram" },
  gangtok: { lat: 27.3389, lng: 88.6065, zoom: 11, name: "East Sikkim (Gangtok)", state: "Sikkim" },
  shillong: { lat: 25.5788, lng: 91.8933, zoom: 11, name: "East Khasi Hills (Shillong)", state: "Meghalaya" },
  guwahati: { lat: 26.1445, lng: 91.7362, zoom: 11, name: "Kamrup Metropolitan (Guwahati)", state: "Assam" },
  kohima: { lat: 25.6751, lng: 94.1086, zoom: 11, name: "Kohima District", state: "Nagaland" },
  itanagar: { lat: 27.0844, lng: 93.6053, zoom: 11, name: "Papum Pare (Itanagar)", state: "Arunachal Pradesh" },
  imphal: { lat: 24.8170, lng: 93.9368, zoom: 11, name: "Imphal West", state: "Manipur" },
  agartala: { lat: 23.8315, lng: 91.2868, zoom: 11, name: "West Tripura (Agartala)", state: "Tripura" },
};

export const EXTENDED_RISK_ZONES: RiskZone[] = [
  {
    id: "zone-aizawl-hunthar",
    districtId: "dist-aizawl",
    districtName: "Aizawl",
    state: "Mizoram",
    name: "Hunthar Veng Slope Corridor",
    zoneCode: "MZ-AZL-01",
    center: { latitude: 23.7385, longitude: 92.7092 },
    currentRiskScore: 87,
    currentRiskLevel: "CRITICAL",
    slopeAngleDeg: 38.5,
    elevationM: 1132,
    soilType: "Silty Clay with weathered shale",
    vegetationCover: "Sparse degraded scrub",
    historicalLandslideCount: 8,
    recentFieldReportCount: 3,
    primaryThreatCorridor: "NH-54 (Silchar-Aizawl Highway)",
    lastEvaluatedAt: new Date().toISOString(),
  },
  {
    id: "zone-aizawl-laipuitlang",
    districtId: "dist-aizawl",
    districtName: "Aizawl",
    state: "Mizoram",
    name: "Laipuitlang Ridge Surcharge",
    zoneCode: "MZ-AZL-02",
    center: { latitude: 23.7428, longitude: 92.7231 },
    currentRiskScore: 78,
    currentRiskLevel: "CRITICAL",
    slopeAngleDeg: 42.0,
    elevationM: 1210,
    soilType: "Friable sandstone & siltstone",
    vegetationCover: "Dense residential building load",
    historicalLandslideCount: 6,
    recentFieldReportCount: 2,
    primaryThreatCorridor: "Bawngkawn-Durtlang Arterial Road",
    lastEvaluatedAt: new Date().toISOString(),
  },
  {
    id: "zone-gangtok-nh10",
    districtId: "dist-gangtok",
    districtName: "Gangtok (East Sikkim)",
    state: "Sikkim",
    name: "29th Mile / Likhuphir Slip Zone",
    zoneCode: "SK-EAS-04",
    center: { latitude: 27.2144, longitude: 88.5238 },
    currentRiskScore: 92,
    currentRiskLevel: "CRITICAL",
    slopeAngleDeg: 44.0,
    elevationM: 920,
    soilType: "Schist & Gneiss overburden",
    vegetationCover: "Terraced slopes & steep road cut",
    historicalLandslideCount: 14,
    recentFieldReportCount: 4,
    primaryThreatCorridor: "NH-10 (Siliguri-Gangtok Lifeline)",
    lastEvaluatedAt: new Date().toISOString(),
  },
  {
    id: "zone-shillong-cherra",
    districtId: "dist-east-khasi",
    districtName: "East Khasi Hills (Shillong)",
    state: "Meghalaya",
    name: "Sohra-Shella Escarpment",
    zoneCode: "ML-EKH-03",
    center: { latitude: 25.2892, longitude: 91.7324 },
    currentRiskScore: 68,
    currentRiskLevel: "HIGH",
    slopeAngleDeg: 35.0,
    elevationM: 1480,
    soilType: "Karstic limestone & laterite",
    vegetationCover: "Subtropical pine & steep shrubs",
    historicalLandslideCount: 11,
    recentFieldReportCount: 1,
    primaryThreatCorridor: "SH-5 Shillong-Cherrapunjee Road",
    lastEvaluatedAt: new Date().toISOString(),
  },
  {
    id: "zone-kohima-dzukou",
    districtId: "dist-kohima",
    districtName: "Kohima",
    state: "Nagaland",
    name: "Phesama-Zubza Bypass Surcharge",
    zoneCode: "NL-KHM-05",
    center: { latitude: 25.6421, longitude: 94.0894 },
    currentRiskScore: 64,
    currentRiskLevel: "HIGH",
    slopeAngleDeg: 33.0,
    elevationM: 1440,
    soilType: "Disruptive Disang shale",
    vegetationCover: "Bamboo and secondary forest",
    historicalLandslideCount: 5,
    recentFieldReportCount: 1,
    primaryThreatCorridor: "NH-29 Kohima-Dimapur Highway",
    lastEvaluatedAt: new Date().toISOString(),
  },
  {
    id: "zone-itanagar-naharlagun",
    districtId: "dist-papum-pare",
    districtName: "Papum Pare (Itanagar)",
    state: "Arunachal Pradesh",
    name: "Banderdewa-Karsingsa Mudflow Point",
    zoneCode: "AR-PAP-07",
    center: { latitude: 27.1240, longitude: 93.6820 },
    currentRiskScore: 72,
    currentRiskLevel: "HIGH",
    slopeAngleDeg: 36.0,
    elevationM: 520,
    soilType: "Unconsolidated Siwalik boulder conglomerate",
    vegetationCover: "Tropical rain forest clearance",
    historicalLandslideCount: 7,
    recentFieldReportCount: 1,
    primaryThreatCorridor: "NH-415 Itanagar Capital Link",
    lastEvaluatedAt: new Date().toISOString(),
  },
  {
    id: "zone-imphal-langol",
    districtId: "dist-imphal-west",
    districtName: "Imphal West",
    state: "Manipur",
    name: "Langol Hillside Fissure Zone",
    zoneCode: "MN-IMP-08",
    center: { latitude: 24.8420, longitude: 93.9110 },
    currentRiskScore: 58,
    currentRiskLevel: "HIGH",
    slopeAngleDeg: 31.0,
    elevationM: 890,
    soilType: "Clayey silt with fine sandstone",
    vegetationCover: "Hilltop human settlements",
    historicalLandslideCount: 3,
    recentFieldReportCount: 0,
    primaryThreatCorridor: "Langol-Lamphel Access Road",
    lastEvaluatedAt: new Date().toISOString(),
  },
  {
    id: "zone-kamrup-maligaon",
    districtId: "dist-kamrup",
    districtName: "Kamrup Metropolitan (Guwahati)",
    state: "Assam",
    name: "Kamakhya Foothill Cut-Slopes",
    zoneCode: "AS-KMR-06",
    center: { latitude: 26.1664, longitude: 91.7051 },
    currentRiskScore: 41,
    currentRiskLevel: "MODERATE",
    slopeAngleDeg: 28.0,
    elevationM: 180,
    soilType: "Red lateritic loam",
    vegetationCover: "Dense human settlement",
    historicalLandslideCount: 4,
    recentFieldReportCount: 0,
    primaryThreatCorridor: "Maligaon-Pandu Road",
    lastEvaluatedAt: new Date().toISOString(),
  },
  {
    id: "zone-tripura-baramura",
    districtId: "dist-west-tripura",
    districtName: "West Tripura (Agartala)",
    state: "Tripura",
    name: "Baramura Range Highway Cut",
    zoneCode: "TR-WTR-09",
    center: { latitude: 23.8510, longitude: 91.5620 },
    currentRiskScore: 22,
    currentRiskLevel: "LOW",
    slopeAngleDeg: 22.0,
    elevationM: 260,
    soilType: "Sandy shale with loose topsoil",
    vegetationCover: "Bamboo grooves and rubber plantation",
    historicalLandslideCount: 2,
    recentFieldReportCount: 0,
    primaryThreatCorridor: "NH-8 Assam-Tripura Highway",
    lastEvaluatedAt: new Date().toISOString(),
  },
];

export const EXTENDED_INFRASTRUCTURE: InfrastructureAsset[] = [
  {
    id: "inf-01",
    districtId: "dist-aizawl",
    name: "Hunthar Valley Bridge & Aqueduct",
    category: "BRIDGE",
    location: { latitude: 23.7390, longitude: 92.7085 },
    vulnerabilityRating: "CRITICAL",
    status: "AT_RISK",
    details: "Abutment threatened by active 12cm slope displacement on NH-54 side.",
  },
  {
    id: "inf-02",
    districtId: "dist-gangtok",
    name: "29th Mile Teesta River Road Bridge",
    category: "BRIDGE",
    location: { latitude: 27.2150, longitude: 88.5230 },
    vulnerabilityRating: "CRITICAL",
    status: "IMPAIRED",
    details: "North pier submerged under 450m³ schist boulder slide.",
  },
  {
    id: "inf-03",
    districtId: "dist-east-khasi",
    name: "Sohra Optical Fiber & Microwave Relay Tower",
    category: "TELECOM_TOWER",
    location: { latitude: 25.2910, longitude: 91.7340 },
    vulnerabilityRating: "HIGH",
    status: "OPERATIONAL",
    details: "Guy-wire anchor foundation positioned 15m from escarpment edge.",
  },
  {
    id: "inf-04",
    districtId: "dist-kohima",
    name: "Zubza 132kV Power Grid Substation",
    category: "POWER_SUBSTATION",
    location: { latitude: 25.6450, longitude: 94.0860 },
    vulnerabilityRating: "HIGH",
    status: "OPERATIONAL",
    details: "Retaining wall drainage requires immediate desiltation.",
  },
];
