import { Alert } from "@/types/alert";

export const MOCK_ALERTS: Alert[] = [
  {
    id: "alt-001",
    title: "RED ALERT: NH-54 Hunthar Landslide Surge",
    severity: "CRITICAL",
    status: "ACTIVE",
    riskScore: 87,
    riskLevel: "CRITICAL",
    districtId: "dist-aizawl",
    districtName: "Aizawl",
    riskZoneId: "zone-aizawl-hunthar",
    riskZoneName: "Hunthar Veng Slope Corridor",
    locationPoint: { latitude: 23.7385, longitude: 92.7092 },
    triggerReason: "Continuous 118mm rainfall in 24h + soil moisture 84.5% + field verification of 12cm transverse fissure across NH-54 highway shoulder.",
    affectedPopulationEstimate: 8400,
    affectedRoads: ["NH-54 (Aizawl-Silchar Corridor)", "Hunthar Link Road"],
    recommendedActions: [
      "Restrict heavy commercial transport immediately on NH-54.",
      "Deploy SDRF Quick Response Team 02 for structural monitoring.",
      "Issue evacuation standby notice for 120 downhill dwellings.",
    ],
    responsePriority: "P1",
    issuedAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    acknowledgedAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    acknowledgedBy: "Duty Officer, Mizoram SDMA",
  },
  {
    id: "alt-002",
    title: "RED ALERT: 29th Mile NH-10 Complete Severance",
    severity: "CRITICAL",
    status: "ACTIVE",
    riskScore: 92,
    riskLevel: "CRITICAL",
    districtId: "dist-gangtok",
    districtName: "Gangtok (East Sikkim)",
    riskZoneId: "zone-gangtok-nh10",
    riskZoneName: "29th Mile / Likhuphir Slip Zone",
    locationPoint: { latitude: 27.2144, longitude: 88.5238 },
    triggerReason: "146mm torrential deluge saturated gneiss bedrock; 450m³ debris actively blocking lifeline NH-10.",
    affectedPopulationEstimate: 14200,
    affectedRoads: ["NH-10 (Siliguri - Gangtok Lifeline)"],
    recommendedActions: [
      "Total transit halt between Rangpo and Singtam.",
      "Reroute essential medical supplies via Lava-Algarah-Reshi pass.",
      "Deploy BRO heavy loaders and excavator units.",
    ],
    responsePriority: "P1",
    issuedAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: "alt-003",
    title: "ORANGE WARNING: Sohra-Shella Escarpment Runoff Alert",
    severity: "WARNING",
    status: "ACTIVE",
    riskScore: 68,
    riskLevel: "HIGH",
    districtId: "dist-east-khasi",
    districtName: "East Khasi Hills (Shillong)",
    riskZoneId: "zone-shillong-cherra",
    riskZoneName: "Sohra-Shella Escarpment",
    locationPoint: { latitude: 25.2892, longitude: 91.7324 },
    triggerReason: "High intensity cloudburst forecast over Sohra catchment; soil saturation at 76%.",
    affectedPopulationEstimate: 3200,
    affectedRoads: ["SH-5 Shillong-Cherrapunjee Road"],
    recommendedActions: [
      "Night travel advisory for tourist vehicles on SH-5.",
      "Village Headman (Rangbah Shnong) alert broadcast.",
    ],
    responsePriority: "P2",
    issuedAt: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
  },
  {
    id: "alt-004",
    title: "YELLOW WATCH: Phesama-Zubza Slope Surcharge",
    severity: "WATCH",
    status: "ACTIVE",
    riskScore: 62,
    riskLevel: "HIGH",
    districtId: "dist-kohima",
    districtName: "Kohima",
    riskZoneId: "zone-kohima-dzukou",
    riskZoneName: "Phesama-Zubza Bypass Surcharge",
    locationPoint: { latitude: 25.6421, longitude: 94.0894 },
    triggerReason: "Disang shale moisture increase following moderate monsoon spell.",
    affectedPopulationEstimate: 1900,
    affectedRoads: ["NH-29 Kohima-Dimapur Bypass"],
    recommendedActions: [
      "Routine highway patrol inspection.",
      "Check culvert silt blockages.",
    ],
    responsePriority: "P3",
    issuedAt: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
  },
];
