import { District } from "@/types/geo";

export const MOCK_DISTRICTS: District[] = [
  {
    id: "dist-aizawl",
    name: "Aizawl",
    state: "Mizoram",
    stateCode: "MZ",
    center: { latitude: 23.7271, longitude: 92.7176 },
    vulnerabilityIndex: 88,
    totalRiskZones: 12,
    criticalZonesCount: 4,
    populationEstimate: 400309,
    areaKm2: 3576,
  },
  {
    id: "dist-east-khasi",
    name: "East Khasi Hills (Shillong)",
    state: "Meghalaya",
    stateCode: "ML",
    center: { latitude: 25.5788, longitude: 91.8933 },
    vulnerabilityIndex: 79,
    totalRiskZones: 15,
    criticalZonesCount: 3,
    populationEstimate: 825922,
    areaKm2: 2748,
  },
  {
    id: "dist-gangtok",
    name: "Gangtok (East Sikkim)",
    state: "Sikkim",
    stateCode: "SK",
    center: { latitude: 27.3389, longitude: 88.6065 },
    vulnerabilityIndex: 92,
    totalRiskZones: 10,
    criticalZonesCount: 4,
    populationEstimate: 283583,
    areaKm2: 954,
  },
  {
    id: "dist-kamrup",
    name: "Kamrup Metropolitan (Guwahati)",
    state: "Assam",
    stateCode: "AS",
    center: { latitude: 26.1445, longitude: 91.7362 },
    vulnerabilityIndex: 64,
    totalRiskZones: 8,
    criticalZonesCount: 1,
    populationEstimate: 1253938,
    areaKm2: 1528,
  },
  {
    id: "dist-kohima",
    name: "Kohima",
    state: "Nagaland",
    stateCode: "NL",
    center: { latitude: 25.6751, longitude: 94.1086 },
    vulnerabilityIndex: 82,
    totalRiskZones: 9,
    criticalZonesCount: 2,
    populationEstimate: 267988,
    areaKm2: 1463,
  },
  {
    id: "dist-papum-pare",
    name: "Papum Pare (Itanagar)",
    state: "Arunachal Pradesh",
    stateCode: "AR",
    center: { latitude: 27.0844, longitude: 93.6053 },
    vulnerabilityIndex: 76,
    totalRiskZones: 11,
    criticalZonesCount: 2,
    populationEstimate: 176573,
    areaKm2: 2875,
  },
  {
    id: "dist-imphal-west",
    name: "Imphal West",
    state: "Manipur",
    stateCode: "MN",
    center: { latitude: 24.8170, longitude: 93.9368 },
    vulnerabilityIndex: 68,
    totalRiskZones: 7,
    criticalZonesCount: 1,
    populationEstimate: 517992,
    areaKm2: 558,
  },
  {
    id: "dist-west-tripura",
    name: "West Tripura (Agartala)",
    state: "Tripura",
    stateCode: "TR",
    center: { latitude: 23.8315, longitude: 91.2868 },
    vulnerabilityIndex: 52,
    totalRiskZones: 6,
    criticalZonesCount: 0,
    populationEstimate: 918200,
    areaKm2: 983,
  },
];
