import { FieldReport } from "@/types/fieldReport";

export const MOCK_FIELD_REPORTS: FieldReport[] = [
  {
    id: "rep-001",
    reporterRole: "FIELD_OFFICER",
    reporterName: "Inspector L. Sailo",
    reporterPhone: "+91 98623 55120",
    riskZoneId: "zone-aizawl-hunthar",
    riskZoneName: "Hunthar Veng Slope Corridor",
    districtId: "dist-aizawl",
    districtName: "Aizawl",
    location: { latitude: 23.7385, longitude: 92.7092 },
    locationAddress: "Hunthar Point, NH-54 bypass milestone 14, Aizawl",
    reportType: "CRACK",
    severity: "CRITICAL",
    observedCracks: true,
    slopeMovementDetected: true,
    roadBlocked: true,
    roadBlockageDegree: "PARTIAL",
    description: "Transverse shear fissure expanding along NH-54 road shoulder. Width approx 12 cm, extending 25 meters across the cut slope.",
    media: [
      {
        id: "med-001",
        url: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80",
        mediaType: "IMAGE",
        visionAnalysis: {
          analyzedAt: new Date().toISOString(),
          source: "Prototype / Simulated Analysis",
          detectedIndicators: [
            { name: "Transverse Slope Cracks", detected: true, confidence: 0.94, severity: "CRITICAL" },
            { name: "Exposed Shear Plane", detected: true, confidence: 0.88, severity: "HIGH" },
            { name: "Active Rockfall Debris", detected: true, confidence: 0.76, severity: "MEDIUM" },
          ],
          overallSeverity: "CRITICAL",
          riskContributionPoints: 24,
          confidenceScore: 0.91,
          recommendedImmediateAction: "Deploy immediate traffic diversion and pre-position earth-moving machinery.",
        },
      },
    ],
    status: "VERIFIED",
    syncStatus: "SYNCED",
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(), // 45 mins ago
    verifiedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    verifiedBy: "State Disaster Control Room, Mizoram",
  },
  {
    id: "rep-002",
    reporterRole: "FIELD_OFFICER",
    reporterName: "J. Dorjee (BRO)",
    reporterPhone: "+91 94340 12890",
    riskZoneId: "zone-gangtok-nh10",
    riskZoneName: "29th Mile / Likhuphir Slip Zone",
    districtId: "dist-gangtok",
    districtName: "Gangtok (East Sikkim)",
    location: { latitude: 27.2144, longitude: 88.5238 },
    locationAddress: "Likhuphir Chute, 29th Mile NH-10",
    reportType: "ROAD_BLOCKED",
    severity: "CRITICAL",
    observedCracks: true,
    slopeMovementDetected: true,
    roadBlocked: true,
    roadBlockageDegree: "COMPLETE",
    description: "Massive boulder slide triggered by heavy downpour. Both lanes obstructed with an estimated 450 cubic meters of schist rubble.",
    media: [
      {
        id: "med-002",
        url: "https://images.unsplash.com/photo-1584467735871-8e85353a8413?auto=format&fit=crop&w=800&q=80",
        mediaType: "IMAGE",
        visionAnalysis: {
          analyzedAt: new Date().toISOString(),
          source: "Prototype / Simulated Analysis",
          detectedIndicators: [
            { name: "Total Highway Blockage", detected: true, confidence: 0.98, severity: "CRITICAL" },
            { name: "Unstable Overhanging Boulders", detected: true, confidence: 0.89, severity: "HIGH" },
          ],
          overallSeverity: "CRITICAL",
          riskContributionPoints: 30,
          confidenceScore: 0.95,
          recommendedImmediateAction: "Declare emergency highway diversion via Lava-Algarah; mobilize heavy rock breakers.",
        },
      },
    ],
    status: "ACTIONED",
    syncStatus: "SYNCED",
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(), // 2 hours ago
    verifiedAt: new Date(Date.now() - 1000 * 60 * 110).toISOString(),
    verifiedBy: "Sikkim SDMA Command",
  },
  {
    id: "rep-003",
    reporterRole: "CITIZEN",
    reporterName: "M. Sangma",
    reporterPhone: "+91 94361 99281",
    riskZoneId: "zone-shillong-cherra",
    riskZoneName: "Sohra-Shella Escarpment",
    districtId: "dist-east-khasi",
    districtName: "East Khasi Hills (Shillong)",
    location: { latitude: 25.2892, longitude: 91.7324 },
    locationAddress: "Upper Sohra rim village path",
    reportType: "EROSION",
    severity: "HIGH",
    observedCracks: true,
    slopeMovementDetected: false,
    roadBlocked: false,
    description: "Runoff water washing away foot trail soil near village retaining wall.",
    media: [],
    status: "PENDING_VERIFICATION",
    syncStatus: "SYNCED",
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
];
