import { ResponseTask } from "@/types/responseTask";

export const MOCK_RESPONSE_TASKS: ResponseTask[] = [
  {
    id: "task-001",
    alertId: "alt-001",
    riskZoneId: "zone-aizawl-hunthar",
    riskZoneName: "Hunthar Veng Slope Corridor",
    districtName: "Aizawl",
    title: "P1: Deploy SDRF Structural Crack Monitor & Restrict NH-54 Lane",
    priority: "P1",
    status: "IN_PROGRESS",
    actionType: "TRAFFIC_DIVERSION",
    assignedAgency: "SDRF 3rd Bn Mizoram & Traffic Police",
    targetLocation: { latitude: 23.7385, longitude: 92.7092 },
    locationDescription: "NH-54 km 14, Hunthar point",
    description: "Install electronic crack displacement pegs, restrict heavy vehicles to alternate Edentlang link, alert 45 families in lower slope.",
    allocatedPersonnel: 18,
    equipmentRequired: ["Geotech Crackmeters", "Barricades", "LED Variable Message Signs", "JCB Earthmover"],
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    estimatedCompletionTime: "Immediate continuous surveillance (24h)",
  },
  {
    id: "task-002",
    alertId: "alt-002",
    riskZoneId: "zone-gangtok-nh10",
    riskZoneName: "29th Mile / Likhuphir Slip Zone",
    districtName: "Gangtok (East Sikkim)",
    title: "P1: Clear 450m³ Rockfall Debris at Likhuphir Chute",
    priority: "P1",
    status: "DEPLOYED",
    actionType: "ROAD_CLEARANCE",
    assignedAgency: "Border Roads Organisation (Project Swastik)",
    targetLocation: { latitude: 27.2144, longitude: 88.5238 },
    locationDescription: "Likhuphir Chute, 29th Mile NH-10",
    description: "Deploy 2 heavy hydraulic rock breakers and 3 dump trucks. Stabilize overhanging boulders before clearing carriageway.",
    allocatedPersonnel: 26,
    equipmentRequired: ["Hydraulic Breaker Excavator", "3x Tippers", "Dozer D85", "Searchlight Towers"],
    createdAt: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    estimatedCompletionTime: "6 to 8 hours depending on rainfall",
  },
  {
    id: "task-003",
    alertId: "alt-003",
    riskZoneId: "zone-shillong-cherra",
    riskZoneName: "Sohra-Shella Escarpment",
    districtName: "East Khasi Hills (Shillong)",
    title: "P2: Drain Desiltation & Slope Runoff Channelization",
    priority: "P2",
    status: "PENDING_DISPATCH",
    actionType: "SLOPE_STABILIZATION",
    assignedAgency: "Meghalaya PWD Roads Division",
    targetLocation: { latitude: 25.2892, longitude: 91.7324 },
    locationDescription: "SH-5 Sohra Ridge",
    description: "Clear clogged cross-drainage culverts to prevent water surcharge from saturating the roadside embankment.",
    allocatedPersonnel: 12,
    equipmentRequired: ["Mini Excavator", "Sandbags (500 units)", "Drain Rodding gear"],
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
];
