import { RiskZone, VulnerableRoad, VulnerableVillage } from "@/types/geo";

export const MOCK_RISK_ZONES: RiskZone[] = [
  {
    id: "zone-aizawl-hunthar",
    districtId: "dist-aizawl",
    districtName: "Aizawl",
    state: "Mizoram",
    name: "Hunthar Veng Slope Corridor",
    zoneCode: "MZ-AZL-01",
    center: { latitude: 23.7385, longitude: 92.7092 },
    currentRiskScore: 87,
    currentRiskLevel: "CRITICAL",
    slopeAngleDeg: 38.5,
    elevationM: 1132,
    soilType: "Silty Clay with weathered shale",
    vegetationCover: "Sparse degraded scrub",
    historicalLandslideCount: 8,
    recentFieldReportCount: 3,
    primaryThreatCorridor: "NH-54 (Silchar-Aizawl Highway)",
    lastEvaluatedAt: new Date().toISOString(),
  },
  {
    id: "zone-aizawl-laipuitlang",
    districtId: "dist-aizawl",
    districtName: "Aizawl",
    state: "Mizoram",
    name: "Laipuitlang Ridge",
    zoneCode: "MZ-AZL-02",
    center: { latitude: 23.7428, longitude: 92.7231 },
    currentRiskScore: 78,
    currentRiskLevel: "CRITICAL",
    slopeAngleDeg: 42.0,
    elevationM: 1210,
    soilType: "Friable sandstone & siltstone",
    vegetationCover: "Dense residential building surcharge",
    historicalLandslideCount: 6,
    recentFieldReportCount: 2,
    primaryThreatCorridor: "Bawngkawn-Durtlang Arterial Road",
    lastEvaluatedAt: new Date().toISOString(),
  },
  {
    id: "zone-shillong-cherra",
    districtId: "dist-east-khasi",
    districtName: "East Khasi Hills (Shillong)",
    state: "Meghalaya",
    name: "Sohra-Shella Escarpment",
    zoneCode: "ML-EKH-03",
    center: { latitude: 25.2892, longitude: 91.7324 },
    currentRiskScore: 68,
    currentRiskLevel: "HIGH",
    slopeAngleDeg: 35.0,
    elevationM: 1480,
    soilType: "Karstic limestone & laterite",
    vegetationCover: "Subtropical pine & shrubs",
    historicalLandslideCount: 11,
    recentFieldReportCount: 1,
    primaryThreatCorridor: "SH-5 Shillong-Cherrapunjee Road",
    lastEvaluatedAt: new Date().toISOString(),
  },
  {
    id: "zone-gangtok-nh10",
    districtId: "dist-gangtok",
    districtName: "Gangtok (East Sikkim)",
    state: "Sikkim",
    name: "29th Mile / Likhuphir Slip Zone",
    zoneCode: "SK-EAS-04",
    center: { latitude: 27.2144, longitude: 88.5238 },
    currentRiskScore: 92,
    currentRiskLevel: "CRITICAL",
    slopeAngleDeg: 44.0,
    elevationM: 920,
    soilType: "Schist & Gneiss overburden",
    vegetationCover: "Terraced slopes & road cut",
    historicalLandslideCount: 14,
    recentFieldReportCount: 4,
    primaryThreatCorridor: "NH-10 (Siliguri-Gangtok Lifeline)",
    lastEvaluatedAt: new Date().toISOString(),
  },
  {
    id: "zone-kohima-dzukou",
    districtId: "dist-kohima",
    districtName: "Kohima",
    state: "Nagaland",
    name: "Phesama-Zubza Bypass Surcharge",
    zoneCode: "NL-KHM-05",
    center: { latitude: 25.6421, longitude: 94.0894 },
    currentRiskScore: 62,
    currentRiskLevel: "HIGH",
    slopeAngleDeg: 33.0,
    elevationM: 1440,
    soilType: "Disrupive Disang shale",
    vegetationCover: "Bamboo and secondary forest",
    historicalLandslideCount: 5,
    recentFieldReportCount: 1,
    primaryThreatCorridor: "NH-29 Kohima-Dimapur Highway",
    lastEvaluatedAt: new Date().toISOString(),
  },
  {
    id: "zone-kamrup-maligaon",
    districtId: "dist-kamrup",
    districtName: "Kamrup Metropolitan (Guwahati)",
    state: "Assam",
    name: "Kamakhya Foothill Cut-Slopes",
    zoneCode: "AS-KMR-06",
    center: { latitude: 26.1664, longitude: 91.7051 },
    currentRiskScore: 41,
    currentRiskLevel: "MODERATE",
    slopeAngleDeg: 28.0,
    elevationM: 180,
    soilType: "Red lateritic loam",
    vegetationCover: "Dense human settlement",
    historicalLandslideCount: 4,
    recentFieldReportCount: 0,
    primaryThreatCorridor: "Maligaon-Pandu Road",
    lastEvaluatedAt: new Date().toISOString(),
  },
];

export const MOCK_ROADS: VulnerableRoad[] = [
  {
    id: "road-nh54",
    districtId: "dist-aizawl",
    roadName: "NH-54 (Aizawl-Silchar Corridor)",
    code: "NH-54",
    classification: "NATIONAL_HIGHWAY",
    importanceWeight: 2.8,
    lengthKm: 48.5,
    isBlocked: true,
    blockageSeverity: "PARTIAL",
    blockageReason: "Debris and tension crack across northbound lane at Hunthar km 14",
    associatedRiskZoneId: "zone-aizawl-hunthar",
    coordinates: [
      { latitude: 23.7271, longitude: 92.7176 },
      { latitude: 23.7385, longitude: 92.7092 },
      { latitude: 23.7550, longitude: 92.6980 },
    ],
  },
  {
    id: "road-nh10",
    districtId: "dist-gangtok",
    roadName: "NH-10 (Siliguri - Gangtok Lifeline)",
    code: "NH-10",
    classification: "NATIONAL_HIGHWAY",
    importanceWeight: 3.0,
    lengthKm: 62.0,
    isBlocked: true,
    blockageSeverity: "TOTAL",
    blockageReason: "Major rockfall and debris accumulation at 29th Mile",
    associatedRiskZoneId: "zone-gangtok-nh10",
    coordinates: [
      { latitude: 27.2144, longitude: 88.5238 },
      { latitude: 27.2750, longitude: 88.5600 },
      { latitude: 27.3389, longitude: 88.6065 },
    ],
  },
];

export const MOCK_VILLAGES: VulnerableVillage[] = [
  {
    id: "vlg-hunthar",
    districtId: "dist-aizawl",
    name: "Hunthar Settlement",
    location: { latitude: 23.7372, longitude: 92.7081 },
    population: 4850,
    households: 620,
    vulnerabilityTier: "CRITICAL",
    nearestShelterDistanceKm: 1.2,
    contactOfficialPhone: "+91 94361 40012",
  },
  {
    id: "vlg-setipool",
    districtId: "dist-gangtok",
    name: "Setipool Hamlet",
    location: { latitude: 27.2401, longitude: 88.5412 },
    population: 2300,
    households: 310,
    vulnerabilityTier: "CRITICAL",
    nearestShelterDistanceKm: 2.5,
    contactOfficialPhone: "+91 94340 55088",
  },
];
