import { WeatherObservation, WeatherForecastDay } from "@/types/weather";

export const MOCK_WEATHER_OBSERVATIONS: Record<string, WeatherObservation> = {
  "zone-aizawl-hunthar": {
    id: "wx-azl-01",
    riskZoneId: "zone-aizawl-hunthar",
    stationName: "IMD Automated AWS - Aizawl Citadel",
    rainfall1hMm: 24.5,
    rainfall6hMm: 68.0,
    rainfall24hMm: 118.5,
    rainfall72hMm: 242.0,
    soilMoisturePct: 84.5,
    temperatureC: 22.4,
    humidityPct: 96.0,
    windSpeedKmh: 28.0,
    dataSource: "IMD_AUTOMATED_WEATHER_STATION",
    observedAt: new Date().toISOString(),
  },
  "zone-gangtok-nh10": {
    id: "wx-sk-02",
    riskZoneId: "zone-gangtok-nh10",
    stationName: "ISRO / CWC AWS - Likhuphir Point",
    rainfall1hMm: 31.0,
    rainfall6hMm: 85.5,
    rainfall24hMm: 146.0,
    rainfall72hMm: 310.0,
    soilMoisturePct: 91.0,
    temperatureC: 18.2,
    humidityPct: 98.0,
    windSpeedKmh: 35.0,
    dataSource: "ISRO_MOSDAC",
    observedAt: new Date().toISOString(),
  },
  "zone-shillong-cherra": {
    id: "wx-ml-03",
    riskZoneId: "zone-shillong-cherra",
    stationName: "IMD AWS - Sohra Meteorological Station",
    rainfall1hMm: 12.0,
    rainfall6hMm: 45.0,
    rainfall24hMm: 88.0,
    rainfall72hMm: 175.0,
    soilMoisturePct: 76.0,
    temperatureC: 19.5,
    humidityPct: 92.0,
    windSpeedKmh: 22.0,
    dataSource: "IMD_AUTOMATED_WEATHER_STATION",
    observedAt: new Date().toISOString(),
  },
};

export const MOCK_FORECAST_DAYS: WeatherForecastDay[] = [
  {
    date: "2026-08-26",
    dayLabel: "Today",
    expectedRainfallMm: 110,
    condition: "HEAVY_MONSOON_DELUGE",
    maxTempC: 24,
    minTempC: 19,
    soilMoistureSaturationRisk: "CRITICAL",
  },
  {
    date: "2026-08-27",
    dayLabel: "Tomorrow",
    expectedRainfallMm: 85,
    condition: "HEAVY_MONSOON_DELUGE",
    maxTempC: 25,
    minTempC: 20,
    soilMoistureSaturationRisk: "HIGH",
  },
  {
    date: "2026-08-28",
    dayLabel: "Day +2",
    expectedRainfallMm: 45,
    condition: "MODERATE_RAIN",
    maxTempC: 26,
    minTempC: 21,
    soilMoistureSaturationRisk: "MODERATE",
  },
  {
    date: "2026-08-29",
    dayLabel: "Day +3",
    expectedRainfallMm: 20,
    condition: "LIGHT_SHOWERS",
    maxTempC: 27,
    minTempC: 21,
    soilMoistureSaturationRisk: "LOW",
  },
];
