export const APP_CONFIG = {
  name: "BHUSHAKTI AI",
  hindiName: "भू-शक्ति AI",
  shortTitle: "Landslide Risk Intelligence",
  fullTitle: "AI-Powered Landslide Early Warning & Risk Monitoring System",
  tagline: "From Environmental Signals to Actionable Warnings — Protecting North Eastern Communities",
  problemStatement: "SIH26001",
  ministry: "Ministry of Development of North Eastern Region (MDoNER)",
  theme: "Disaster Management",
  version: "1.0.0-prototype",
  nerStates: [
    "Arunachal Pradesh",
    "Assam",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Sikkim",
    "Tripura",
  ],
  defaultCenter: {
    latitude: 25.5788,
    longitude: 91.8933, // Shillong / NER geographic center
    zoom: 7,
  },
  thresholds: {
    rainfallDelugeMm24h: 100,
    soilMoistureSaturationPct: 75,
    criticalSlopeAngleDeg: 35,
  },
  routes: [
    {
      title: "Landing Page",
      href: "/",
      iconName: "Home",
      roles: ["ADMIN", "FIELD_OFFICER", "CITIZEN"],
    },
    {
      title: "Command Center",
      href: "/dashboard",
      iconName: "LayoutDashboard",
      badge: "Live",
      roles: ["ADMIN", "FIELD_OFFICER"],
    },
    {
      title: "Disaster Simulation",
      href: "/simulation",
      iconName: "Flame",
      badge: "DEMO",
      badgeVariant: "critical",
      highlight: true,
      roles: ["ADMIN", "FIELD_OFFICER", "CITIZEN"],
    },
    {
      title: "GIS Risk Map",
      href: "/map",
      iconName: "Map",
      badge: "Heatmap",
      roles: ["ADMIN", "FIELD_OFFICER", "CITIZEN"],
    },
    {
      title: "AI Risk Analytics",
      href: "/risk",
      iconName: "BrainCircuit",
      roles: ["ADMIN", "FIELD_OFFICER"],
    },
    {
      title: "Active Alerts",
      href: "/alerts",
      iconName: "AlertTriangle",
      badge: "4 Active",
      badgeVariant: "critical",
      roles: ["ADMIN", "FIELD_OFFICER", "CITIZEN"],
    },
    {
      title: "Field Reports",
      href: "/reports",
      iconName: "FileText",
      roles: ["ADMIN", "FIELD_OFFICER"],
    },
    {
      title: "Response Matrix",
      href: "/response",
      iconName: "ShieldAlert",
      badge: "P1-P4",
      roles: ["ADMIN"],
    },
    {
      title: "24h Forecast",
      href: "/forecast",
      iconName: "CloudRain",
      roles: ["ADMIN", "FIELD_OFFICER", "CITIZEN"],
    },
    {
      title: "Submit Field Report",
      href: "/field-report",
      iconName: "Camera",
      highlight: true,
      roles: ["ADMIN", "FIELD_OFFICER", "CITIZEN"],
    },
    {
      title: "System Settings",
      href: "/settings",
      iconName: "Settings",
      roles: ["ADMIN"],
    },
  ],
};
